spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: SA
    password:
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create-drop